=== hmcts/cpp-context-prosecution-documentqueue/documentqueue-domain/documentqueue-domain-core/src/raml/json/schema/document.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://justice.gov.uk/prosecution/documentqueue/domain/document.json",
  "type": "object",
  "properties": {
    "scanDocumentId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "caseUrn": {
      "type": "string"
    },
    "casePTIUrn": {
      "type": "string"
    },
    "prosecutorAuthorityId": {
      "type": "string",
      "maxLength": 8
    },
    "prosecutorAuthorityCode": {
      "type": "string"
    },
    "documentControlNumber": {
      "type": "string"
    },
    "documentName": {
      "type": "string"
    },
    "scanningDate": {
      "$ref": "http://cpp.moj.gov.uk/core/domain/json/schema/data-types.json#/definitions/date-time"
    },
    "manualIntervention": {
      "type": "string"
    },
    "envelopeId": {
      "type": "string"
    },
    "source": {
      "type": "string",
      "$ref": "http://justice.gov.uk/prosecution/documentqueue/domain/enums/source.json"
    },
    "fileName": {
      "type": "string"
    },
    "zipFileName": {
      "type": "string"
    },
    "notes": {
      "type": "string"
    },
    "vendorReceivedDate": {
      "$ref": "http://cpp.moj.gov.uk/core/domain/json/schema/data-types.json#/definitions/date-time"
    },
    "status": {
      "type": "string",
      "$ref": "http://justice.gov.uk/prosecution/documentqueue/domain/enums/status.json"
    },
    "type": {
      "type": "string",
      "$ref": "http://justice.gov.uk/prosecution/documentqueue/domain/enums/type.json"
    },
    "statusUpdatedDate": {
      "$ref": "http://cpp.moj.gov.uk/core/domain/json/schema/data-types.json#/definitions/date-time"
    },
    "userId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "actionedBy": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "materialId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "fileServiceId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "receivedDateTime": {
      "$ref": "http://cpp.moj.gov.uk/core/domain/json/schema/data-types.json#/definitions/date-time"
    },
    "externalDocumentId": {
      "type": "string"
    },
    "statusCode": {
      "type": "string"
    },
    "caseId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    }
  },
  "required": [
    "scanDocumentId",
    "fileName",
    "status"
  ],
  "additionalProperties": false
}

=== hmcts/cpp-context-prosecution-documentqueue/documentqueue-event/documentqueue-event-listener/src/yaml/json/documentqueue.events.outstanding-document-received.json
{
  "scanDocumentId": "c78cb222-58d0-42ac-9cc8-d1b2710171bf",
  "caseUrn": "TVL6794003OMW",
  "prosecutorAuthorityId": "GAEAA01",
  "prosecutorAuthorityCode": "TVL",
  "documentControlNumber": "54856456",
  "documentName": "SJPMC100",
  "fileName": "financial_means_with_ocr_data.pdf",
  "manualIntervention": "No",
  "vendorReceivedDate": "2020-02-12T20:11:32.013Z",
  "scanningDate": "2020-02-12T20:51:32.013Z",
  "notes": "These are file notes for testing",
  "envelopeId": "285256e4-23df-475c-87ac-c0dc031349bf",
  "zipFileName": "bae5ffba-80e6-4baa-9a10-8a88460e941f.zip",
  "source": "BULKSCAN",
  "status": "OUTSTANDING",
  "type": "FINANCIAL_MEANS",
  "statusUpdatedDate": "2020-02-12T20:51:32.013Z"
}
