=== hmcts/cpp-context-prosecution-documentqueue/documentqueue-event/documentqueue-event-processor/src/yaml/json/schema/public.prosecutioncasefile.material-added.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://moj.gov.uk/cpp/json/schemas/prosecutioncasefile/events/public.prosecutioncasefile.material-added.json",
  "type": "object",
  "properties": {
    "caseId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "prosecutingAuthority": {
      "type": "string"
    },
    "prosecutorDefendantId": {
      "type": "string",
      "maxLength": 36
    },
    "defendantId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "defendantName": {
      "type": "string"
    },
    "material": {
      "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/material.json"
    },
    "caseType": {
      "type": "string"
    },
    "documentTypeId": {
      "type": "string"
    },
    "documentType": {
      "type": "string"
    },
    "documentCategory": {
      "type": "string"
    },
    "isCpsCase":{
      "type":"boolean"
    },
    "cmsDocumentIdentifier": {
      "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/cms-document-identifier.json"
    },
    "receivedDateTime":{
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/date-time"
    },
    "sectionCode": {
      "type": "string"
    }
  },
  "required": [
    "caseId",
    "material",
    "caseType"
  ],
  "additionalProperties": false
}

=== hmcts/cpp-context-prosecution-documentqueue/documentqueue-integration-test/src/test/resources/json/documentqueue/public.prosecutioncasefile.material-added.json
{
  "caseId": "${caseId}",
  "prosecutingAuthority": "TFLOUCODE",
  "prosecutorDefendantId": "TFL_DEF001",
  "material": {
    "fileStoreId": "${fileStoreId}",
    "documentType": "SJPN"
  },
  "isCpsCase":false,
  "cmsDocumentIdentifier": {
    "materialType": 1,
    "documentId": "ABCDEF"
  },
  "caseType": "CC",
  "receivedDateTime": "2020-02-04T05:27:17.210Z"
}

=== hmcts/cpp-context-prosecution-documentqueue/documentqueue-command/documentqueue-command-handler/src/test/resources/json/materialAdded.json
{
  "caseId": "51cac7fb-387c-4d19-9c80-8963fa8cf222",
  "caseType": "UNKNOWN",
  "documentType": "SJPN",
  "material": {
    "documentType": "SJPN",
    "fileStoreId": "3042a896-fd3e-478d-bb0e-948dd46191a4",
    "fileType": "application/pdf"
  },
  "prosecutingAuthority": "TVLOUCODE",
  "prosecutorDefendantId": "TVL_DEF001",
  "isCpsCase": false
}
