=== hmcts/cpp-context-prosecution-documentqueue/documentqueue-event/documentqueue-event-processor/src/yaml/json/schema/public.prosecutioncasefile.document-review-required.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://moj.gov.uk/cps/prosecutioncasefile/domain/event/public.prosecutioncasefile.document-review-required",
  "type": "object",
  "properties": {
    "fileStoreId": {
      "$ref": "http://cpp.moj.gov.uk/core/domain/json/schema/data-types.json#/definitions/uuid"
    },
    "receivedDateTime":{
      "$ref": "http://cpp.moj.gov.uk/core/domain/json/schema/data-types.json#/definitions/date-time"
    },
    "cmsDocumentId": {
      "type": "string"
    },
    "source": {
      "type": "string"
    },
    "prosecutingAuthority": {
      "type": "string"
    },
    "caseId": {
      "$ref": "http://cpp.moj.gov.uk/core/domain/json/schema/data-types.json#/definitions/uuid"
    },
    "documentType": {
      "type": "string",
      "enum": [
        "APPLICATION",
        "CORRESPONDENCE",
        "PLEA",
        "OTHER"
      ]
    },
    "errorCodes": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "required": [
    "fileStoreId"
  ],
  "additionalProperties": true
}

=== hmcts/cpp-context-prosecution-documentqueue/documentqueue-integration-test/src/test/resources/json/documentqueue/public.prosecutioncasefile.document-review-required.json
{
  "fileStoreId": "${fileStoreId}",
  "receivedDateTime": "2020-01-20T13:50:00Z",
  "cmsDocumentId": "45b0c3fe-afe6-4652-882f-7882d79eadd9",
  "source": 	"CPS",
  "documentType": "OTHER",
  "caseId": "45b0c3fe-afe6-4652-882f-7882d79eadd9",
  "errorCodes": [
    "reasonCode1",
    "reasonCode2"
  ]
}
