=== hmcts/cpp-context-prosecution-documentqueue/documentqueue-event/documentqueue-event-processor/src/yaml/json/schema/public.progression.document-review-required.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://moj.gov.uk/cps/progression/domain/event/public.progression.document-review-required",
  "type": "object",
  "properties": {
    "materialId": {
      "$ref": "http://cpp.moj.gov.uk/core/domain/json/schema/data-types.json#/definitions/uuid"
    },
    "receivedDateTime": {
      "$ref": "http://cpp.moj.gov.uk/core/domain/json/schema/data-types.json#/definitions/date-time"
    },
    "documentId": {
      "$ref": "http://cpp.moj.gov.uk/core/domain/json/schema/data-types.json#/definitions/uuid"
    },
    "documentName": {
      "type": "string"
    },
    "caseId": {
      "$ref": "http://cpp.moj.gov.uk/core/domain/json/schema/data-types.json#/definitions/uuid"
    },
    "source": {
      "type": "string",
      "$ref": "http://justice.gov.uk/prosecution/documentqueue/domain/enums/source.json"
    },
    "urn": {
      "type": "string"
    },
    "prosecutingAuthority": {
      "type": "string"
    },
    "documentType": {
      "type": "string"
    },
    "code": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "additionalProperties": true
}

=== hmcts/cpp-context-prosecution-documentqueue/documentqueue-event/documentqueue-event-processor/src/yaml/json/public.progression.document-review-required.json
{
  "materialId": "45b0c3fe-afe6-4652-882f-7882d79eadd9",
  "receivedDateTime": "2020-01-20T13:50:00Z",
  "documentId": "45b0c3fe-afe6-4652-882f-7882d79eadd9",
  "documentName":"DocumentName1",
  "source": "OTHER",
  "urn": "abcd123",
  "prosecutingAuthority": "abc",
  "documentType": "Applications",
  "code": [
    "uploaded-review-required"
  ]
}
